apiVersion: v1
kind: Service
metadata:
  name: subscription-service
spec:
  type: LoadBalancer
  selector:
    app: subscription  # This should match the label of your deployment
  ports:
  - port: 80             # Port exposed by the service
    targetPort: 9696     # Port inside the container
